name: DP-SimplePrefix
version: 2.0.0
main: com.darksoldier1404.dsp.SimplePrefix
api-version: 1.16
authors: [ DEAD_POOLIO_ ]
depend:
  - DPP-Core
softdepend:
  - LuckPerms
  - Vault
commands:
  dsp:
    aliases: [simpleprefix]