name: DP-SimplePrefix
version: 1.0.1.4
main: com.darksoldier1404.dsp.SimplePrefix
api-version: 1.14
authors: [ DEAD_POOLIO_ ]
depend:
  - DPP-Core
softdepend:
  - LuckPerms
  - Vault
commands:
  dsp:
    aliases: [simpleprefix]